### ISSUE TITLE
Define Top level folder / directory

### ISSUE THREAD

**Issue by Steve2Go** [dredkin/deluge-rbb#15]
Hey there, amazing addition - literally the reason I switched to Deluge.

Just to make it easier for less technical users (ie the wife), can we add an option preference (perhaps in browserbuttton.conf) to define a new root folder - ie I want to restrict users to the download drive, without access to put things into system folder.

Or does this exist undocumented already?

Cheers.

**Comment by Mattie432** [comment]
Hi Steve,
I'm looking into this hopefully will be able to send you a prototype for testing soon (maybe tomorrow).

**Comment by Steve2Go** [comment]
You are my new hero :)

Kind regards,
Steve

**Comment by Mattie432** [comment]
Hi Steve,
If you would kindly like to test [this release](https://github.com/Mattie432/deluge-rbb/releases) and report any bugs/problems.

Thanks!

**Comment by Steve2Go** [comment]
Thank you!

Will do as soon as I get home later

Kind regards,
Steve

**Comment by Steve2Go** [comment]
Hi there.

Setting is available, but has no effect.

Tested server using 2.7 linux, client using 2.7 Windows

Kind Regards,

Steve

**Comment by Mattie432** [comment]
Hi, any logs/info available? Can you look at the browsebutton.conf file to see if the settings are present. Does clicking the browse button in the preferences pane work? Did you check the "disable traversal" box in the preferences pane?

Thanks,
Matt

**Comment by Steve2Go** [comment]
Problem solved!

The check box isn't immediately obvious - scrolling sideways is needed to
see it in a non maximised window.

Perhaps it may help to put it below the text area?

Works fantastic though! Thank you so much (now I found the setting)

Kind regards,
Steve

**Comment by Mattie432** [comment]
Oh that's interesting! would you mind attaching a screenshot? It's supposed to be relative to the right side of the window (and not go off the screen :) ). 

Glad you have it working, if you encounter any other problems please let me know.

**Comment by Steve2Go** [comment]
No problem, see attached

[image: Inline images 1][image: Inline images 2]

Kind Regards,

Steve

**Comment by Mattie432** [comment]
Unfortunately the images didn't make it, I believe github strips all html and attachments from email replies. Could you send them to matt@mattie432.com or upload to an image host and post the links?

Thanks

**Comment by Steve2Go** [comment]
Hi Mattie, FYI I sent that email a few days back - you may want to check spam

**Comment by Mattie432** [comment]
Thanks, I did receive it. It looks to happen because the internal pref pane will not resize as small as the window. I think you would be in a minority with this occurring as most people do not have their window so small. 

I have not changed the ui but will add a screenshot of the preferences pane so others will know what to expect.

**Comment by Mattie432** [comment]
Hi Steve, have there been any problems with this version? If not i'll push it as a release, thanks!

**Comment by Steve2Go** [comment]
Still working great, thanks

Kind regards,
Steve
