### ISSUE TITLE
Version v.0.1.10 crashes GTK-UI

### ISSUE THREAD

**Issue by Grewfisk** [dredkin/deluge-rbb#18]
I've been using the browsebutton-0.1.9-py2.7.egg successfully on my client and server. When I attempted to install browsebutton-0.1.10-py2.7.egg my GTK GUI crashes. This has happened with multiple setups now. I've double checked that I have the right python version installed on client and server. I can give you some logs if I could figure out where to find them.

**Comment by dredkin** [comment]
Server can be started with logging like:
`deluged -d [-L <loglevel>] [-l <logfile>]`
client:
on windows: `deluge-debug.exe [-L <loglevel>] [-l <logfile>]`
on linux `deluge -L <loglevel> -l <logfile>`:
if you have ubuntu, server logs are usually in /var/log/deluged
But since yo've got problems on client, that must be client issue.
[More info on logs](http://dev.deluge-torrent.org/wiki/Faq#HowdoIstartthedaemonwithloggingenabled).

**Comment by Grewfisk** [comment]
Okay here's the log from the client when using browsebutton-0.1.10-py2.7.egg

`** (deluge:11588): CRITICAL **: unity_gtk_menu_shell_get_item: assertion '0 <= index && index < items->len' failed

** (deluge:11588): CRITICAL **: unity_gtk_menu_item_get_child_shell: assertion 'UNITY_GTK_IS_MENU_ITEM (item)' failed

** (deluge:11588): CRITICAL **: unity_gtk_menu_shell_get_item: assertion '0 <= index && index < items->len' failed

** (deluge:11588): CRITICAL **: unity_gtk_menu_item_get_label: assertion 'UNITY_GTK_IS_MENU_ITEM (item)' failed

** (deluge:11588): CRITICAL **: unity_gtk_menu_item_get_icon: assertion 'UNITY_GTK_IS_MENU_ITEM (item)' failed
Segmentation fault (core dumped)
`

**Comment by Mattie432** [comment]
Can you log more than just the *critical* errors & maybe include more lines for greater context.

**Comment by Grewfisk** [comment]
deluge -L debug
[INFO    ] 20:37:10 main:125 Deluge ui 1.3.12
[DEBUG   ] 20:37:10 main:126 options: {'loglevel': 'debug', 'default_ui': None, 'args': None, 'quiet': False, 'ui': None, 'logfile': None, 'config': None}
[DEBUG   ] 20:37:10 main:127 args: []
[DEBUG   ] 20:37:10 main:128 ui_args: []
[INFO    ] 20:37:10 main:131 Starting ui..
[DEBUG   ] 20:37:10 ui:129 UI init..
[DEBUG   ] 20:37:10 configmanager:111 Getting config 'ui.conf'
[DEBUG   ] 20:37:10 config:197 Setting 'default_ui' to gtk of <type 'str'>
[DEBUG   ] 20:37:10 config:391 Config /home/user/.config/deluge/ui.conf version: 1.1 loaded: {'default_ui': u'gtk'}
[INFO    ] 20:37:10 ui:148 Starting GtkUI..
[WARNING ] 20:37:10 gtkui:207 Unable to register a 'die' handler with the GNOME session manager: No module named gnome.ui
[DEBUG   ] 20:37:10 common:250 gconf not available, so will not attempt to register magnet uri handler
[DEBUG   ] 20:37:10 configmanager:111 Getting config 'gtkui.conf'
[DEBUG   ] 20:37:10 config:197 Setting 'close_to_tray' to False of <type 'bool'>
[DEBUG   ] 20:37:10 config:197 Setting 'ntf_sound_path' to /home/user/Downloads of <type 'str'>
[DEBUG   ] 20:37:10 config:197 Setting 'window_width' to 640 of <type 'int'>
[DEBUG   ] 20:37:10 config:197 Setting 'default_load_path' to None of <type 'NoneType'>
[DEBUG   ] 20:37:10 config:197 Setting 'window_y_pos' to 0 of <type 'int'>
[DEBUG   ] 20:37:10 config:197 Setting 'ntf_email' to False of <type 'bool'>
[DEBUG   ] 20:37:10 config:197 Setting 'tray_upload_speed_list' to [5.0, 10.0, 30.0, 80.0, 300.0] of <type 'list'>
[DEBUG   ] 20:37:10 config:197 Setting 'show_statusbar' to True of <type 'bool'>
[DEBUG   ] 20:37:10 config:197 Setting 'ntf_popup' to False of <type 'bool'>
[DEBUG   ] 20:37:10 config:197 Setting 'ntf_pass' to  of <type 'str'>
[DEBUG   ] 20:37:10 config:197 Setting 'tray_download_speed_list' to [5.0, 10.0, 30.0, 80.0, 300.0] of <type 'list'>
[DEBUG   ] 20:37:10 config:197 Setting 'window_maximized' to False of <type 'bool'>
[DEBUG   ] 20:37:10 config:197 Setting 'enable_system_tray' to True of <type 'bool'>
[DEBUG   ] 20:37:10 config:197 Setting 'show_sidebar' to True of <type 'bool'>
[DEBUG   ] 20:37:10 config:197 Setting 'show_connection_manager_on_start' to True of <type 'bool'>
[DEBUG   ] 20:37:10 config:197 Setting 'lock_tray' to False of <type 'bool'>
[DEBUG   ] 20:37:10 config:197 Setting 'createtorrent.trackers' to [] of <type 'list'>
[DEBUG   ] 20:37:10 config:197 Setting 'ntf_sound' to False of <type 'bool'>
[DEBUG   ] 20:37:10 config:197 Setting 'tray_password' to  of <type 'str'>
[DEBUG   ] 20:37:10 config:197 Setting 'focus_add_dialog' to True of <type 'bool'>
[DEBUG   ] 20:37:10 config:197 Setting 'ntf_server' to  of <type 'str'>
[DEBUG   ] 20:37:10 config:197 Setting 'start_in_tray' to False of <type 'bool'>
[DEBUG   ] 20:37:10 config:197 Setting 'ntf_tray_blink' to True of <type 'bool'>
[DEBUG   ] 20:37:10 config:197 Setting 'check_new_releases' to False of <type 'bool'>
[DEBUG   ] 20:37:10 config:197 Setting 'autoadd_queued' to False of <type 'bool'>
[DEBUG   ] 20:37:10 config:197 Setting 'pref_dialog_width' to None of <type 'NoneType'>
[DEBUG   ] 20:37:10 config:197 Setting 'autoadd_enable' to False of <type 'bool'>
[DEBUG   ] 20:37:10 config:197 Setting 'autoconnect_host_id' to None of <type 'NoneType'>
[DEBUG   ] 20:37:10 config:197 Setting 'classic_mode' to True of <type 'bool'>
[DEBUG   ] 20:37:10 config:197 Setting 'window_pane_position' to -1 of <type 'int'>
[DEBUG   ] 20:37:10 config:197 Setting 'enabled_plugins' to [] of <type 'list'>
[DEBUG   ] 20:37:10 config:197 Setting 'show_rate_in_title' to False of <type 'bool'>
[DEBUG   ] 20:37:10 config:197 Setting 'pref_dialog_height' to None of <type 'NoneType'>
[DEBUG   ] 20:37:10 config:197 Setting 'ntf_username' to  of <type 'str'>
[DEBUG   ] 20:37:10 config:197 Setting 'interactive_add' to True of <type 'bool'>
[DEBUG   ] 20:37:10 config:197 Setting 'sidebar_show_zero' to False of <type 'bool'>
[DEBUG   ] 20:37:10 config:197 Setting 'window_x_pos' to 0 of <type 'int'>
[DEBUG   ] 20:37:10 config:197 Setting 'window_height' to 480 of <type 'int'>
[DEBUG   ] 20:37:10 config:197 Setting 'ntf_security' to None of <type 'NoneType'>
[DEBUG   ] 20:37:10 config:197 Setting 'connection_limit_list' to [50, 100, 200, 300, 500] of <type 'list'>
[DEBUG   ] 20:37:10 config:197 Setting 'sidebar_position' to 170 of <type 'int'>
[DEBUG   ] 20:37:10 config:197 Setting 'show_new_releases' to False of <type 'bool'>
[DEBUG   ] 20:37:10 config:197 Setting 'autoconnect' to False of <type 'bool'>
[DEBUG   ] 20:37:10 config:197 Setting 'choose_directory_dialog_path' to /home/user/Downloads of <type 'str'>
[DEBUG   ] 20:37:10 config:197 Setting 'sidebar_show_trackers' to True of <type 'bool'>
[DEBUG   ] 20:37:10 config:197 Setting 'autostart_localhost' to False of <type 'bool'>
[DEBUG   ] 20:37:10 config:197 Setting 'show_toolbar' to True of <type 'bool'>
[DEBUG   ] 20:37:10 config:197 Setting 'autoadd_location' to  of <type 'str'>
[DEBUG   ] 20:37:10 config:197 Setting 'enable_appindicator' to True of <type 'bool'>
[DEBUG   ] 20:37:10 config:197 Setting 'focus_main_window_on_add' to True of <type 'bool'>
[DEBUG   ] 20:37:10 config:197 Setting 'ntf_email_add' to  of <type 'str'>
[DEBUG   ] 20:37:10 config:197 Setting 'signal_port' to 40000 of <type 'int'>
[DEBUG   ] 20:37:10 config:391 Config /home/user/.config/deluge/gtkui.conf version: 1.1 loaded: {'close_to_tray': False, 'ntf_sound_path': u'/home/user/Downloads', 'window_width': 1738, 'default_load_path': None, 'window_y_pos': 24, 'ntf_email': False, 'tray_upload_speed_list': [5.0, 10.0, 30.0, 80.0, 976.0], 'show_statusbar': True, 'ntf_popup': False, 'ntf_pass': u'', 'show_sidebar': True, 'window_maximized': False, 'enable_system_tray': True, 'tray_download_speed_list': [5.0, 10.0, 30.0, 80.0, 5900.0], 'show_connection_manager_on_start': False, 'lock_tray': False, 'createtorrent.trackers': [], 'ntf_sound': False, 'tray_password': u'', 'focus_add_dialog': True, 'ntf_server': u'', 'start_in_tray': False, 'ntf_tray_blink': True, 'check_new_releases': False, 'pref_dialog_height': 557, 'autoadd_queued': False, 'pref_dialog_width': 659, 'autoconnect_host_id': u'cd994cbd9a9b51f55decb05277c662cc80d89ccf', 'classic_mode': False, 'window_pane_position': 583, 'focus_main_window_on_add': True, 'show_rate_in_title': False, 'autoadd_enable': False, 'ntf_username': u'', 'interactive_add': True, 'sidebar_show_zero': True, 'window_x_pos': 71, 'window_height': 1028, 'ntf_security': None, 'connection_limit_list': [50, 100, 200, 300, 500], 'sidebar_position': 183, 'show_new_releases': False, 'autoconnect': True, 'choose_directory_dialog_path': u'/home/user/Downloads', 'sidebar_show_trackers': True, 'autostart_localhost': False, 'show_toolbar': True, 'autoadd_location': u'', 'enable_appindicator': True, 'enabled_plugins': [], 'ntf_email_add': u'', 'signal_port': 40000}
[DEBUG   ] 20:37:10 configmanager:111 Getting config 'gtkui.conf'
[DEBUG   ] 20:37:10 ipcinterface:127 Checking if lockfile exists: /home/user/.config/deluge/ipc/deluge-gtk.lock
[DEBUG   ] 20:37:10 ipcinterface:181 Processing args from other process: []
[DEBUG   ] 20:37:10 ipcinterface:184 Not connected to host.. Adding to queue.
[DEBUG   ] 20:37:10 sessionproxy:55 SessionProxy init..
[DEBUG   ] 20:37:10 configmanager:111 Getting config 'gtkui.conf'
[DEBUG   ] 20:37:10 config:304 Registering function for show_rate_in_title key..
[DEBUG   ] 20:37:10 menubar:53 MenuBar init..
[DEBUG   ] 20:37:10 configmanager:111 Getting config 'gtkui.conf'
[DEBUG   ] 20:37:10 toolbar:51 ToolBar Init..
[DEBUG   ] 20:37:10 configmanager:111 Getting config 'gtkui.conf'
[DEBUG   ] 20:37:10 listview:192 ListView initialized..
[DEBUG   ] 20:37:10 listview:323 Loading ListView state file: torrentview.state
/usr/lib/python2.7/dist-packages/deluge/ui/gtkui/listview.py:250: GtkWarning: gtk_tree_model_sort_set_sort_column_id: assertion 'header != NULL' failed
  self.treeview.get_model().set_sort_column_id(column_state.sort, column_state.sort_order)
[DEBUG   ] 20:37:10 torrentview:222 TorrentView Init..
[DEBUG   ] 20:37:10 torrentdetails:443 Loading TorrentDetails state file: tabs.state
[DEBUG   ] 20:37:10 torrentdetails:157 weights: []
[DEBUG   ] 20:37:10 torrentdetails:158 weight of tab: 0
[DEBUG   ] 20:37:10 torrentdetails:193 Trying to insert tab at -1
[DEBUG   ] 20:37:10 torrentdetails:69 parent: None
[DEBUG   ] 20:37:10 torrentdetails:198 Tab inserted at 0
[DEBUG   ] 20:37:10 files_tab:280 Loading FilesTab state file: files_tab.state
[DEBUG   ] 20:37:10 torrentdetails:157 weights: [(0, 'Status')]
[DEBUG   ] 20:37:10 torrentdetails:158 weight of tab: 2
[DEBUG   ] 20:37:10 torrentdetails:193 Trying to insert tab at -1
[DEBUG   ] 20:37:10 torrentdetails:69 parent: None
[DEBUG   ] 20:37:10 torrentdetails:198 Tab inserted at 1
[DEBUG   ] 20:37:10 peers_tab:211 Loading PeersTab state file: peers_tab.state
[DEBUG   ] 20:37:10 torrentdetails:157 weights: [(0, 'Status'), (2, 'Files')]
[DEBUG   ] 20:37:10 torrentdetails:158 weight of tab: 3
[DEBUG   ] 20:37:10 torrentdetails:193 Trying to insert tab at -1
[DEBUG   ] 20:37:10 torrentdetails:69 parent: None
[DEBUG   ] 20:37:10 torrentdetails:198 Tab inserted at 2
[DEBUG   ] 20:37:10 torrentdetails:157 weights: [(0, 'Status'), (2, 'Files'), (3, 'Peers')]
[DEBUG   ] 20:37:10 torrentdetails:158 weight of tab: 1
[DEBUG   ] 20:37:10 torrentdetails:164 Found pos 1
[DEBUG   ] 20:37:10 torrentdetails:193 Trying to insert tab at 1
[DEBUG   ] 20:37:10 torrentdetails:69 parent: None
[DEBUG   ] 20:37:10 torrentdetails:198 Tab inserted at 1
[DEBUG   ] 20:37:10 torrentdetails:157 weights: [(0, 'Status'), (1, 'Details'), (2, 'Files'), (3, 'Peers')]
[DEBUG   ] 20:37:10 torrentdetails:158 weight of tab: 4
[DEBUG   ] 20:37:10 torrentdetails:193 Trying to insert tab at -1
[DEBUG   ] 20:37:10 torrentdetails:69 parent: None
[DEBUG   ] 20:37:10 torrentdetails:198 Tab inserted at 4
[DEBUG   ] 20:37:10 configmanager:111 Getting config 'gtkui.conf'
[DEBUG   ] 20:37:10 configmanager:111 Getting config 'gtkui.conf'
[DEBUG   ] 20:37:10 sidebar:85 add tab:filters
[DEBUG   ] 20:37:10 filtertreeview:322 nothing selected
[DEBUG   ] 20:37:10 configmanager:111 Getting config 'gtkui.conf'
[DEBUG   ] 20:37:10 configmanager:111 Getting config 'gtkui.conf'
[DEBUG   ] 20:37:10 config:304 Registering function for enable_system_tray key..
[DEBUG   ] 20:37:10 systemtray:109 Enabling the Application Indicator..
[DEBUG   ] 20:37:10 config:304 Registering function for enable_appindicator key..
[DEBUG   ] 20:37:10 configmanager:111 Getting config 'gtkui.conf'
[DEBUG   ] 20:37:10 configmanager:111 Getting config 'gtkui.conf'
[DEBUG   ] 20:37:10 pluginmanagerbase:65 Plugin manager init..
[DEBUG   ] 20:37:10 configmanager:111 Getting config 'gtkui.conf'
[DEBUG   ] 20:37:10 pluginmanagerbase:124 Found plugin: Extractor 0.4 at /usr/lib/python2.7/dist-packages/deluge/plugins/Extractor-0.4.egg
[DEBUG   ] 20:37:10 pluginmanagerbase:124 Found plugin: Execute 1.3 at /usr/lib/python2.7/dist-packages/deluge/plugins/Execute-1.3.egg
[DEBUG   ] 20:37:10 pluginmanagerbase:124 Found plugin: Blocklist 1.3 at /usr/lib/python2.7/dist-packages/deluge/plugins/Blocklist-1.3.egg
[DEBUG   ] 20:37:10 pluginmanagerbase:124 Found plugin: AutoAdd 1.4 at /usr/lib/python2.7/dist-packages/deluge/plugins/AutoAdd-1.4.egg
[DEBUG   ] 20:37:10 pluginmanagerbase:124 Found plugin: Label 0.2 at /usr/lib/python2.7/dist-packages/deluge/plugins/Label-0.2.egg
[DEBUG   ] 20:37:10 pluginmanagerbase:124 Found plugin: Notifications 0.2 at /usr/lib/python2.7/dist-packages/deluge/plugins/Notifications-0.2.egg
[DEBUG   ] 20:37:10 pluginmanagerbase:124 Found plugin: WebUi 0.1 at /usr/lib/python2.7/dist-packages/deluge/plugins/WebUi-0.1.egg
[DEBUG   ] 20:37:10 pluginmanagerbase:124 Found plugin: Scheduler 0.2 at /usr/lib/python2.7/dist-packages/deluge/plugins/Scheduler-0.2.egg
[DEBUG   ] 20:37:10 pluginmanagerbase:124 Found plugin: browsebutton 0.1.10 at /home/user/.config/deluge/plugins/browsebutton-0.1.10-py2.7.egg
[DEBUG   ] 20:37:10 configmanager:111 Getting config 'gtkui.conf'
[DEBUG   ] 20:37:10 configmanager:111 Getting config 'hostlist.conf.1.2'
[DEBUG   ] 20:37:10 config:197 Setting 'hosts' to [('f35a5fbb90db31f2c7d175ae16965080c16b164e', '127.0.0.1', 58846, '', '')] of <type 'list'>
[DEBUG   ] 20:37:10 config:391 Config /home/user/.config/deluge/hostlist.conf.1.2 version: 1.1 loaded: {'hosts': [[u'cd994cbd9a9b51f55decb05277c662cc80d89ccf', u'127.0.0.1', 58846, u'', u'']]}
[DEBUG   ] 20:37:10 gtkui:334 _on_reactor_start
[DEBUG   ] 20:37:10 mainwindow:107 Showing window
[DEBUG   ] 20:37:10 config:216 Setting 'window_pane_position' to 756 of <type 'int'>
[DEBUG   ] 20:37:10 systemtray:409 _on_window_show
[DEBUG   ] 20:37:10 systemtray:360 on_menuitem_show_deluge_activate
[DEBUG   ] 20:37:11 config:216 Setting 'window_x_pos' to 61 of <type 'int'>
[DEBUG   ] 20:37:11 config:216 Setting 'window_x_pos' to 71 of <type 'int'>
[DEBUG   ] 20:37:11 config:216 Setting 'window_pane_position' to 583 of <type 'int'>
[INFO    ] 20:37:11 client:217 Connecting to daemon at 127.0.0.1:58846..
[INFO    ] 20:37:11 client:121 Connected to daemon at 127.0.0.1:58846..
[DEBUG   ] 20:37:11 pluginmanager:88 Core has these plugins enabled: ('browsebutton',)
[DEBUG   ] 20:37:11 pluginbase:62 GtkPlugin initialized..
/home/user/.config/deluge/plugins/browsebutton-0.1.10-py2.7.egg/browsebutton/gtkui.py:262: Warning: g_ptr_array_insert: assertion 'index_ <= (gint)rarray->len' failed

** (deluge:12447): CRITICAL **: unity_gtk_menu_shell_get_item: assertion '0 <= index && index < items->len' failed

** (deluge:12447): CRITICAL **: unity_gtk_menu_item_get_child_shell: assertion 'UNITY_GTK_IS_MENU_ITEM (item)' failed

** (deluge:12447): CRITICAL **: unity_gtk_menu_shell_get_item: assertion '0 <= index && index < items->len' failed

** (deluge:12447): CRITICAL **: unity_gtk_menu_item_get_label: assertion 'UNITY_GTK_IS_MENU_ITEM (item)' failed

** (deluge:12447): CRITICAL **: unity_gtk_menu_item_get_icon: assertion 'UNITY_GTK_IS_MENU_ITEM (item)' failed
Segmentation fault (core dumped)

**Comment by Mattie432** [comment]
Okay, looks like an issue inserting the menu item into the right click connect menu. Possible *out-by-one* error though the whole method to insert into context menu could do with a re-write.

**Comment by dredkin** [comment]
I've just updated to 1.3.15 and in my client there is NO "move storage" label in context menu of a torrent. I don't know why but this explains the crash. You could add a check if index of menu item is >= 0 before inserting it to a menu. This _could_ fix the crash.
