### ISSUE TITLE
Deluge 2.0.3

### ISSUE THREAD

**Issue by labaland** [dredkin/deluge-rbb#21]
Is it possible to add support for it ? =)

**Comment by dredkin** [comment]
I'd like to if someone would tell me where can I get it for windows.

**Comment by niXta1** [comment]
> I'd like to if someone would tell me where can I get it for windows.
It's not perfect yet but you can find it here:
https://forum.deluge-torrent.org/viewtopic.php?f=12&t=55463

**Comment by dredkin** [comment]
Thank you! I'll give it a try.

**Comment by dredkin** [comment]
Wow... so many changes in 2.x! This can take a awhile...

**Comment by dredkin** [comment]
Here is the alpha version of RBB for deluge 2. Please test
https://yadi.sk/d/yUvJG2PcgoeSoA

The code varies heavily from 1.3 version, it will take time to make a release...

**Comment by dredkin** [comment]
So, no feedback at all?
I'm attaching a pre-release version of the plugin. If nobody will answer I'll make it a release.
https://yadi.sk/d/F0Zqi0Iva0Bdxw
