### ISSUE TITLE
Support for py3.8?

### ISSUE THREAD

**Issue by niXta1** [dredkin/deluge-rbb#22]
Thanks for the update (#21)! 👍

Can you add a py3.8.egg plugin file?

Br, niXta

**Comment by dredkin** [comment]
I don't have any, sorry.
You can make it by yourself, following the instruction in readme:
1. git clone ...
2. cd deluge-rbb
3. python3.8 ./setup.py bdist_egg
4. The .egg file is in the dist subfolder.

**Comment by dredkin** [comment]
I've managed to install python3.8.
Look in Releases.

**Comment by niXta1** [comment]
> I've managed to install python3.8.
> Look in Releases.

As far as I understand it, 3.8 has brought no incompatibilities with 3.7. So it should be possible to just rename 3.7 to 3.8.

I also saw that you had compiled it for 3.8 now, thank you!
