### ISSUE TITLE
Support for Python 3.9

### ISSUE THREAD

**Issue by returnedinformation** [dredkin/deluge-rbb#25]
Well it's been a year! If there's any chances you haven't abandoned the plugin, I really hope that giving us a support for Python 3.9 won't be a big trouble for you!

**Comment by dredkin** [comment]
Please provide info what is wrong with 3.9 ?
Did you try to follow the instructions to build  and .egg from source (see *Building* section of Readme)?

**Comment by returnedinformation** [comment]
> 
> 
> Please provide info what is wrong with 3.9 ?
> Did you try to follow the instructions to build and .egg from source (see _Building_ section of [Readme](https://github.com/dredkin/deluge-rbb/blob/master/README.md#Building))?

Yes, you're right, sorry it's been a while since I came here and forgot there is an option to Build it yourself. Seems my problem is that I have downloaded new unofficial Windows Deluge that runs on Python 3.9, but my server runs on 3.8... Everything works except the plugin. I suppose I'll have to make the Deluge on my Ubuntu server run somehow with 3.9

**Comment by dredkin** [comment]
Actually, running different versions of python on client and server never was a problem. Did you try to install both versions of the plugin as it is said in the [Installation](https://github.com/dredkin/deluge-rbb/blob/master/README.md#installation) section?

**Comment by returnedinformation** [comment]
I don't think your plugin is the issue at this point. I've tried using this unofficial installation and plugin didn't work with it: https://forum.deluge-torrent.org/viewtopic.php?f=12&t=55776

Both client and server were Python 3.8 and still haven't had luck. I've downgraded to the version of Deluge that worked properly for me and now I'm fine with it. I'll wait for the official release of Deluge 2.0 for Windows (if it ever happens), and I'm waiting for some stable Linux Distro with 5.10 kernel support. I used Manjaro but after some update it just stopped working.

**Comment by dredkin** [comment]
Please [turn on](https://dev.deluge-torrent.org/wiki/Troubleshooting#EnableDelugeLogging) log files collection on both client and server (loglevel=debug), reproduce the bug and post it here (or on e.g. pastebin if it is too long).

**Comment by returnedinformation** [comment]
Well... seems you ain't giving up on me so easily...
Here... I hope I logged it properly:
Windows client (deluge-2.0.3-lt1.2.10-boost1.74-py3.8.5-ossl1.1.1g-GTK3.24.23)
https://pastebin.com/RYBUb8aH
Linux server
https://pastebin.com/Hd60cPdW

**Comment by dredkin** [comment]
The log says your current Deluge client theme misses some images I use. I can try to handle this error.

**Comment by dredkin** [comment]
please try this and post new logs if this file fails. https://disk.yandex.ru/d/RERmyI6QsE2oLw

**Comment by returnedinformation** [comment]
ohh... I actually thought that that might be the only thing that I can try to fix the issue... but I thought it might be irrelevant...
Sorry for not trying earlier.

I've tried it just now and it works! Thank you very much for the solution

**Comment by returnedinformation** [comment]
Sorry, I now realized I wasn't specific: I tried the plugin you've sent me and it works now
