### ISSUE TITLE
New plugin eggs?

### ISSUE THREAD

**Issue by returnedinformation** [dredkin/deluge-rbb#26]
Can we get new eggs for Python 3.12?
Been using your plugin for a long time, it's making Deluge usable

**Comment by dredkin** [comment]
I don't use Deluge for years  now.
Also, I don't have python 3.12 on my machine.
Have you tried the instructions on building your own .egg (see readme on the front page)?
I could guide you through the process if you want.

**Comment by returnedinformation** [comment]
Oh, I'm making a standard case of RTFM... Thanks, will make my own egg!
You've moved to using another client or you don't use torrent in general anymore?

EDIT: Well, it took me 2 minutes... sorry for disturbance, it's working now!

**Comment by dredkin** [comment]
I use transmission because it consumes less resources on my seedbox.
Glad to hear it.
